[build]
command = "npm run build"
publish = "build"

[build.environment]
NODE_VERSION = "18"
REACT_APP_API_BASE_URL = "https://ulgur-backend-production-53b2.up.railway.app/webapp"
DISABLE_ESLINT_PLUGIN = "true"
